name:                vague
version:             0.1.0.0
github:              "githubuser/vague"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vague#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- array
- utf8-string
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-patterns
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving
- LambdaCase

library:
  source-dirs: src
  dependencies:
  - regex-pcre
  - vector
  - unordered-containers
  - directory
  - filepath
  - llvm-hs
  - llvm-hs-pure

executables:
  vague-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vague
    - optparse-applicative

tests:
  vague-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-golden
    - vague
