name: Simple test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('*.yaml') }}
    - name: Setup Haskell stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
        stack setup
    - name: Test
      run: stack test
